### ISSUE TITLE
Broken API link on Visualizations > Data page

### ISSUE THREAD

**Issue by meagdoh** [m-lab/mlab-vis-client#272]
**newbie here**

[(https://github.com/m-lab/mlab-vis-client/blob/master/src/containers/DataPage/DataPage.jsx#L539
)]
Currently, links to https://data-api-dot-mlab-oti.appspot.com/ which did not work for me. Should be: http://data-api.measurementlab.net/

May be a conflict with the `apiROOT` 
In config.js,   `apiRoot: process.env.APIROOT || '//data-api.measurementlab.net/'`
In package.json, `APIROOT": "//data-api-dot-mlab-oti.appspot.com`

**Comment by georgiamoon** [comment]
@meagdoh if you want to make the change and do a PR @critzo or I can review it

**Comment by critzo** [comment]
If I recall correctly, https for the API web front-end was not implemented
because the vis client app has permissions to query it directly and the
front-end was put up simply for convenience to view its various parameters.

I assume the desired functionality is to allow other clients to query the
API for data? We may simply need to add a cert for the front-end to provide
open https access. A client app could likely also use a service account
that is given explicit access to query the API service running in appengine
I think.

Happy also to talk more about this and review pull requests.

**Comment by georgiamoon** [comment]
@critzo it's just that it's the appspot link and not m-lab link. the HTTPS issue is different and true, but relates to some dependencies for the loading of the API page.

**Comment by mlab-code-reviews** [comment]
We could simply replace the href to "http://data-api.measurementlab.net/"
but that removes the reference to the config files...

@critzo I'll ping you today about this.
